apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/mgj/.minikube/ca.crt
    server: https://192.168.64.17:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/mgj/.minikube/apiserver.crt
    client-key: /Users/mgj/.minikube/apiserver.key

#
spec:
  # containers:
  #   - name: mysqldev
  #     image: mysql/mysql-server:5.6.32
  #     ports:
  #       - containerPort: 3306
  #         hostPort: 3306
  #     volumeMounts:
  #       - mountPath: "/var/lib/mysql"
  #         name: volumesnew
  volumes:
    - name: server
      hostPath:
        path: "/Volumes/proton/work/loop/server"
