#! /bin/sh

export TERM="xterm-256color"
#export LSCOLORS=exfxcxdxbxegedabagacad
export CLICOLOR=1
export LSCOLORS=gxfxcxexbxegedabaggCgd


export PATH=/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/X11/bin
export PATH=/usr/local/bin:/usr/local/sbin:$PATH:~/.bin:~/bin:/opt/bin:/opt/.bin
export PATH=/usr/local/share/npm/bin:$PATH
#export PATH=/Applications/Postgres.app/Contents/MacOS/bin:$PATH
#export PATH=$PATH:/usr/local/Cellar/phantomjs/1.6.1/bin

export HOSTNAME=$HOST

# export NODE_PATH="$HOME/lib/node_modules"

# export ANDROID_HOME=~/Library/Android/sdk
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/platform-tools

#export PATH=~/.work/py:~/.work:$PATH
##
### npm
##
#export CC="/usr/bin/gcc"
#export CXX="/usr/bin/g++"
#export LD="/usr/bin/gcc"


##
## scipy
##
#export CC=clang
#export CXX=clang
#export FFLAGS=-ff2


#export CXX=/usr/local/bin/g++-4.7
#export CC=/usr/local/bin/gcc-4.7
#export CPP=/usr/local/bin/cpp-4.7
#export LD=/usr/local/bin/ld
#export FFLAGS="-ff2c"

# export PYTHONPATH=/usr/local/lib/python:$PYTHONPATH
# export PYTHONSTARTUP=~/.pythonrc
# export DYLD_LIBRARY_PATH=/usr/local/Cellar/icu4c/4.8.1/include
